name: DTAP - Dev Branch Check

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (debug mode)
        run: mvn clean test -X
        working-directory: Jabberpoint-IT-main/jabberpoint-main

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
        working-directory: Jabberpoint-IT-main/jabberpoint-main

  acceptance:
    name: Acceptance Check
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Echo Acceptance Step
        run: echo "Simulated Acceptance Step – Add deployment checks, UAT triggers, etc."