name: DTAP - Feature Branch Quality Check

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build-test:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean verify
        working-directory: Jabberpoint-IT-main/jabberpoint-main

  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run PMD analysis
        run: mvn pmd:pmd
        working-directory: Jabberpoint-IT-main/jabberpoint-main

  security-scan:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install OWASP Dependency-Check
        run: |
          mkdir dependency-check
          curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -o dc.zip
          unzip dc.zip -d dependency-check

      - name: Run security scan
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh --project "JabberPoint" --scan Jabberpoint-IT-main/jabberpoint-main --format HTML --out reports
        shell: bash