name: DTAP - Main Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests with Maven
        run: mvn clean verify
        working-directory: Jabberpoint-IT-main/jabberpoint-main

  acceptance:
    name: Acceptance Check
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Echo Acceptance Step
        run: echo "Simulated Acceptance Step – Add deployment checks, UAT triggers, etc."

  production-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: acceptance
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Echo Production Deployment
        run: echo "Deploying to Production... (Simulated)"